// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVVeMGMkssW-cp3QcqI4AoAWIw-Qk33uk',
    appId: '1:891691718664:web:e5393af87d606f751459bd',
    messagingSenderId: '891691718664',
    projectId: 'home-workers-fa5cd',
    authDomain: 'home-workers-fa5cd.firebaseapp.com',
    storageBucket: 'home-workers-fa5cd.firebasestorage.app',
    measurementId: 'G-6ZKT5L630T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByZ_z2fq2TGRKZKFcKrPrEEacLEttpdCY',
    appId: '1:891691718664:android:411e6ffdbd1e617d1459bd',
    messagingSenderId: '891691718664',
    projectId: 'home-workers-fa5cd',
    storageBucket: 'home-workers-fa5cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABCQg9Q_tGSFpw004GmrSDveWK7GEG5vY',
    appId: '1:891691718664:ios:ab0df72ac220feed1459bd',
    messagingSenderId: '891691718664',
    projectId: 'home-workers-fa5cd',
    storageBucket: 'home-workers-fa5cd.firebasestorage.app',
    iosBundleId: 'com.example.homeWorkersFe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABCQg9Q_tGSFpw004GmrSDveWK7GEG5vY',
    appId: '1:891691718664:ios:ab0df72ac220feed1459bd',
    messagingSenderId: '891691718664',
    projectId: 'home-workers-fa5cd',
    storageBucket: 'home-workers-fa5cd.firebasestorage.app',
    iosBundleId: 'com.example.homeWorkersFe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVVeMGMkssW-cp3QcqI4AoAWIw-Qk33uk',
    appId: '1:891691718664:web:7753c1c6251e8ca51459bd',
    messagingSenderId: '891691718664',
    projectId: 'home-workers-fa5cd',
    authDomain: 'home-workers-fa5cd.firebaseapp.com',
    storageBucket: 'home-workers-fa5cd.firebasestorage.app',
    measurementId: 'G-40G62HJD6L',
  );
}
